### ISSUE TITLE
Open/Close Sensors

### ISSUE THREAD

**Issue by InZan3** [silviokennecke/homebridge-gpio-garage-door#1]
Could you please add support for open/close Sensors?

**Comment by silviokennecke** [comment]
Funny, you request that. I just added one to my garage door just last weekend. How will your sensor work? Via GPIO or is a HTTP Webhook also okay?

**Comment by InZan3** [comment]
i have 2 Garage Doors hardwired to my Raspberry, so I need GPIO :-) If you add these two Sensors it could be one of the best Plugins for Homebridge :-) to now I use GPIO Homebridge Plugin but with that im stuck on Node 10.19 :-(

**Comment by jak1502** [comment]
I would support this too. Currently have a magnetic reed switch to check for open/close. Would be a good feature to add.

**Comment by silviokennecke** [comment]
I just published 0.1.0-beta.3. You can test it.
Warning: As I implemented it yesterday evening in a hurry, I was not able to test it myself.

**Comment by silviokennecke** [comment]
I just tested it today and added a small thing I missed. I just released the version 1.0.0.
I would therefore consider this ticket as resolved.
